### ISSUE TITLE
Some books are not found.

### ISSUE THREAD

**Issue by hibenji** [garzj/d4sd#2]
Most books work perfectly, but there are some that are just not found for some reason.

As you see the Prime Time one is not found by your tool, but global is.
<img width="466" alt="error" src="https://user-images.githubusercontent.com/65447501/191491598-b2fe3929-0c6d-4561-85c5-a0ac423b1e6a.png">

Both are in my account and working.
<img width="565" alt="book" src="https://user-images.githubusercontent.com/65447501/191491100-76c6543c-11cc-4c6a-b8cb-f71abbb1eea3.png">

Any reason why this could be happening.
It could also be quite useful if you could just specify the URL of the book like this: `https://a.digi4school.at/ebook/6415/1001`

**Comment by garzj** [comment]
Would be nice if you inspect the mystic book and show me some html. Maybe the `a` tag is nested inside some other element between the `#shelf` parent.

Anyways, I just published a new relase, so that you can now specify book urls instead of titles. Make sure to use Left click -> Coy link address in your shelf, so that authentication works correctly. Let me know if this solved it for you.

**Comment by hibenji** [comment]
Heya,

Thanks for the update.

Using URLs works perfectly. 👍 

If you are interested the inspect from both books.

Working Book:
<img width="368" alt="image" src="https://user-images.githubusercontent.com/65447501/191632867-fb82785e-70d5-46a4-bbb9-7dc1b53e028b.png">

Not Working Book: (works with URL tho)
<img width="362" alt="image" src="https://user-images.githubusercontent.com/65447501/191632903-b1c87410-6843-4f97-ae6e-cab2101108e6.png">
